"""
TOOL REGISTRY
=============
Maps string tool names → callable Python functions.

The executor looks up tools here by name at runtime.
The synthesis engine registers new tools here at runtime.

This is what "capability synthesis at runtime" means concretely:
new Python functions (generated by the LLM) get added to TOOL_REGISTRY
while the agent is running, and can be used by subsequent steps in the
same session. They also persist to capability_memory.json so they are
re-registered on the next startup without re-synthesis.

The registry is intentionally a plain dict (not a class) so:
- Lookups are O(1)
- New entries are a single dict assignment
- The entire registry is inspectable with list(TOOL_REGISTRY.keys())
"""
from tools.workflows import (
    list_workflows, get_workflow, get_workflow_by_name,
    create_workflow, update_workflow, activate_workflow,
    deactivate_workflow, delete_workflow,
)
from tools.executions import (
    list_executions, get_execution,
    get_recent_executions_for_workflow,
    get_failed_executions, delete_execution,
)
from tools.node_types import get_installed_node_types
from tools.credentials import (
    list_credentials, get_credential,
    delete_credential, create_credential,
)

TOOL_REGISTRY: dict = {
    # ── Workflow CRUD ──────────────────────────────────────
    "list_workflows": list_workflows,
    "get_workflow": get_workflow,
    "get_workflow_by_name": get_workflow_by_name,
    "create_workflow": create_workflow,
    "update_workflow": update_workflow,
    "activate_workflow": activate_workflow,
    "deactivate_workflow": deactivate_workflow,
    "delete_workflow": delete_workflow,

    # ── Execution queries ──────────────────────────────────
    "list_executions": list_executions,
    "get_execution": get_execution,
    "get_recent_executions_for_workflow": get_recent_executions_for_workflow,
    "get_failed_executions": get_failed_executions,
    "delete_execution": delete_execution,

    # ── Node types ─────────────────────────────────────────
    "get_installed_node_types": get_installed_node_types,

    # ── Credentials ────────────────────────────────────────
    "list_credentials": list_credentials,
    "get_credential": get_credential,
    "delete_credential": delete_credential,
    "create_credential": create_credential,
}


def get_tool(name: str):
    """Return tool function or None if not found. None signals a capability gap."""
    return TOOL_REGISTRY.get(name)


def register_tool(name: str, func) -> None:
    """
    Register a tool (built-in or synthesised) in the live registry.
    Synthesised tools added here are available immediately for the rest of the session.
    """
    TOOL_REGISTRY[name] = func
    print(f"[Registry] Registered: {name}")


def list_tool_names() -> list:
    """Return all currently registered tool names."""
    return list(TOOL_REGISTRY.keys())


def describe_tools() -> dict:
    """Return a dict of tool names → docstrings for use in the planner prompt."""
    result = {}
    for name, fn in TOOL_REGISTRY.items():
        doc = fn.__doc__ or ""
        # Take just the first line of the docstring
        first_line = doc.strip().split("\n")[0].strip()
        result[name] = first_line
    return result